# Generated by Django 3.0.3 on 2020-03-03 17:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.IntegerField(choices=[(0, '店員'), (1, '店長')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=1024)),
                ('site_url', models.CharField(blank=True, max_length=2048)),
                ('tel', models.CharField(max_length=128)),
                ('tel2', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': '飲食店',
                'verbose_name_plural': '飲食店',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('eatery.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StoreManger',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('eatery.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('number', models.CharField(max_length=128, unique=True)),
                ('accomodation', models.PositiveIntegerField()),
                ('start_using_at', models.DateTimeField(verbose_name='使用開始時間')),
                ('status', models.ImageField(choices=[(0, '空き'), (1, '予約'), (2, '使用中')], default=0, upload_to='')),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.Eatery')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=512, verbose_name='商品名')),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.Eatery')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('products', models.ManyToManyField(to='eatery.Product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.Table')),
            ],
            options={
                'verbose_name': '請求',
                'verbose_name_plural': '請求',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('reserved_date', models.DateField(verbose_name='予約日')),
                ('reserved_time', models.TimeField(verbose_name='予約時刻')),
                ('status', models.IntegerField(choices=[(0, '待ち'), (1, '来店確認完了'), (2, 'キャンセル')], default=0)),
                ('name', models.CharField(max_length=1024)),
                ('tel', models.CharField(max_length=128)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eatery.Invoice')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.Table')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eatery.Staff')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
