# Generated by Django 3.0.3 on 2020-03-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eatery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eatery.Eatery'),
            preserve_default=False,
        ),
    ]
