# Generated by Django 3.0.3 on 2020-03-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '未処理'), (1, '配膳済み')], default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.IntegerField(choices=[(0, '未処理'), (1, '決済終了')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('eatery', 'ordering')},
        ),
    ]
