# Generated by Django 3.0.3 on 2020-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0002_product_eatery'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
