# Generated by Django 3.0.3 on 2020-03-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0002_auto_20200305_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('eatery', 'number')},
        ),
    ]
