# Generated by Django 3.0.3 on 2020-03-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0003_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
