# Generated by Django 3.0.3 on 2020-03-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0004_auto_20200303_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='local_drink', max_length=128),
            preserve_default=False,
        ),
    ]
